name: Go Packages Test

on:
  push:
#    branches:
#      - master
#    paths:
#      - go/**
  pull_request:
    paths:
      - go/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...
      working-directory: ./go

    - name: Test
      run: go test -v ./...
      working-directory: ./go
